src/main/java/io/github/cadenceoss/iwf/core/Client.java
src/main/java/io/github/cadenceoss/iwf/core/JacksonJsonObjectEncoder.java
src/main/java/io/github/cadenceoss/iwf/core/ObjectEncoder.java
src/main/java/io/github/cadenceoss/iwf/core/WorkerService.java
src/main/java/io/github/cadenceoss/iwf/core/mapper/SignalResultMapper.java
src/main/java/io/github/cadenceoss/iwf/core/mapper/StateMovementMapper.java

https://github.com/cadence-oss/iwf-java-sdk/issues/16

refactor object encoder

---

build.gradle
src/main/java/io/github/cadenceoss/iwf/core/Client.java
src/main/java/io/github/cadenceoss/iwf/core/StateDecision.java
src/main/java/io/github/cadenceoss/iwf/core/StateMovement.java
src/main/java/io/github/cadenceoss/iwf/core/command/CommandRequest.java
src/main/java/io/github/cadenceoss/iwf/core/mapper/CommandRequestMapper.java
src/main/java/io/github/cadenceoss/iwf/core/mapper/TimerCommandMapper.java
src/test/java/io/github/cadenceoss/iwf/integ/IntegrationTest.java
src/test/java/io/github/cadenceoss/iwf/integ/WorkflowRegistry.java
src/test/java/io/github/cadenceoss/iwf/integ/query/BasicQueryWorkflow.java
src/test/java/io/github/cadenceoss/iwf/integ/query/BasicQueryWorkflowState1.java
src/test/java/io/github/cadenceoss/iwf/integ/signal/BasicSignalWorkflow.java
src/test/java/io/github/cadenceoss/iwf/integ/signal/BasicSignalWorkflowState1.java
src/test/java/io/github/cadenceoss/iwf/integ/timer/BasicTimerWorkflow.java
src/test/java/io/github/cadenceoss/iwf/integ/timer/BasicTimerWorkflowState1.java
src/test/java/io/github/cadenceoss/iwf/spring/controller/ApiController.java

Refactoring:
1. Update IDL to get rid of non supported feature
2. Refactor integ test
Testing:
All tests passed with local iwf-server

Support timer feature and refactor code

---

src/main/java/io/iworkflow/core/WorkflowState.java

https://github.com/indeedeng/iwf-java-sdk/issues/100

Fix stateOption comment for the default timeout and format

---

src/main/java/io/iworkflow/core/Client.java
src/main/java/io/iworkflow/core/Registry.java
src/main/java/io/iworkflow/core/UnregisteredClient.java
src/main/java/io/iworkflow/core/UnregisteredWorkflowOptions.java
src/main/java/io/iworkflow/core/WorkflowOptions.java
src/test/java/io/iworkflow/integ/BasicTest.java
src/test/java/io/iworkflow/integ/InterStateTest.java
src/test/java/io/iworkflow/integ/PersistenceTest.java
src/test/java/io/iworkflow/integ/SignalTest.java
src/test/java/io/iworkflow/integ/TimerTest.java

https://github.com/indeedeng/iwf-java-sdk/issues/103
https://github.com/indeedeng/iwf-java-sdk/issues/99

Refactor WorkflowOptions and startWorkflow API to be simpler

---

src/main/java/io/iworkflow/core/persistence/DataAttributesRWImpl.java
src/test/java/io/iworkflow/integ/RpcTest.java
src/test/java/io/iworkflow/integ/rpc/RpcWorkflow.java

for https://github.com/indeedeng/iwf-java-sdk/issues/164

Allow setting nulls to data attributes

---

src/main/java/io/iworkflow/core/Client.java
src/main/java/io/iworkflow/core/UnregisteredClient.java
src/main/java/io/iworkflow/core/UnregisteredWorkflowOptions.java
src/main/java/io/iworkflow/core/WorkflowOptionBuilderExtension.java
src/main/java/io/iworkflow/core/WorkflowOptions.java
src/main/java/io/iworkflow/core/WorkflowState.java

Closes https://github.com/indeedeng/iwf/issues/403

Upgrade waitForCompletionState to wait for all executions

---

src/main/java/io/iworkflow/core/InvalidStateDecisionException.java
src/main/java/io/iworkflow/core/WorkerService.java
src/test/java/io/iworkflow/integ/RpcTest.java
src/test/java/io/iworkflow/integ/WorkflowUncompletedTest.java
src/test/java/io/iworkflow/integ/statedecision/EmptyStateDecisionWorkflow.java
src/test/java/io/iworkflow/spring/controller/ApiController.java

Reject empty StateDecision

---

src/main/java/io/iworkflow/core/Client.java
src/main/java/io/iworkflow/core/IwfHttpException.java
src/main/java/io/iworkflow/core/exceptions/ClientSideException.java
src/main/java/io/iworkflow/core/exceptions/LongPollTimeoutException.java
src/main/java/io/iworkflow/core/exceptions/WorkflowAlreadyStartedException.java
src/main/java/io/iworkflow/core/exceptions/WorkflowNotExistsOrOpenException.java
src/test/java/io/iworkflow/integ/BasicTest.java
src/test/java/io/iworkflow/integ/RpcTest.java
src/test/java/io/iworkflow/integ/SignalTest.java
src/test/java/io/iworkflow/integ/WorkflowUncompletedTest.java

Add new ClientSideExceptions

---

src/main/java/io/iworkflow/core/Client.java
src/main/java/io/iworkflow/core/ClientSideException.java
src/main/java/io/iworkflow/core/IwfHttpException.java
src/main/java/io/iworkflow/core/exceptions/LongPollTimeoutException.java
src/main/java/io/iworkflow/core/exceptions/WorkflowAlreadyStartedException.java
src/main/java/io/iworkflow/core/exceptions/WorkflowNotExistsOrOpenException.java
src/test/java/io/iworkflow/integ/RpcTest.java

Move ClientSideException back to io.iworkflow.core

---

src/test/java/io/iworkflow/integ/BasicTest.java
src/test/java/io/iworkflow/spring/controller/ApiController.java

No code change needed as the IDL is backward compatible. 

Sync IDL to latest

---

src/main/java/io/iworkflow/core/command/CommandRequest.java
src/main/java/io/iworkflow/core/exceptions/CommandNotFoundException.java
src/test/java/io/iworkflow/integ/AnyCommandCombinationTest.java
src/test/java/io/iworkflow/integ/anycommandcombination/AnyCommandCombinationFailWorkflow.java
src/test/java/io/iworkflow/integ/anycommandcombination/InvalidAnyCommandCombinationWorkflowState.java

Depends on https://github.com/indeedeng/iwf/pull/423

IWF-102: Require commandId to exist for ANY_COMMAND_COMBINATION_COMPLETED

---

README.md
src/main/java/io/iworkflow/core/Client.java
src/main/java/io/iworkflow/core/UnregisteredClient.java

See also https://github.com/indeedeng/iwf/issues/439

Remove broken and unused methods and return parameters for waitForStateExecutionCompletion

---

build.gradle
src/main/java/io/iworkflow/core/JacksonJsonObjectEncoder.java

Simplify the encoding type for default encoder

---

build.gradle

Bump release version to 2.6.2

---

src/main/java/io/iworkflow/core/Client.java
src/main/java/io/iworkflow/core/UnregisteredClient.java
src/main/java/io/iworkflow/core/UnregisteredWorkflowOptions.java
src/main/java/io/iworkflow/core/WorkflowOptions.java

IWF-119: Add workflowAlreadyStartedOptions

---

build.gradle

IWF-302: Bump release version to 2.6.4

---

src/main/java/io/iworkflow/core/Client.java
src/main/java/io/iworkflow/core/UnregisteredClient.java
src/main/java/io/iworkflow/core/UnregisteredWorkflowOptions.java
src/main/java/io/iworkflow/core/WorkflowOptions.java
src/test/java/io/iworkflow/integ/PersistenceTest.java
src/test/java/io/iworkflow/integ/persistence/BasicPersistenceWorkflow.java

Support initial data attribute on startWorkflow

---

build.gradle

IWF-315: Updated to latest release version

---

src/main/java/io/iworkflow/core/StateDecision.java

fixed in https://github.com/indeedeng/iwf/pull/490

Remove outdated TODO as the issue is fixed

---

src/main/java/io/iworkflow/core/ResetWorkflowTypeAndOptions.java
src/main/java/io/iworkflow/core/UnregisteredClient.java
src/test/java/io/iworkflow/integ/ResetTest.java
src/test/java/io/iworkflow/integ/rpc/RpcLockingWorkflow.java
src/test/java/io/iworkflow/integ/rpc/RpcLockingWorkflowState1.java
src/test/java/io/iworkflow/integ/rpc/RpcLockingWorkflowState2.java

IWF-336: add skip update method for reset

---

build.gradle

IWF-380: Bump release version to 2.7.1

---

src/main/java/io/iworkflow/core/command/CommandRequest.java

NOBUG: add overloaded methods with List of commands for CommandRequest

---

src/main/java/io/iworkflow/core/WorkerService.java
src/main/java/io/iworkflow/core/communication/Communication.java
src/main/java/io/iworkflow/core/communication/CommunicationImpl.java
src/test/java/io/iworkflow/integ/RpcTest.java
src/test/java/io/iworkflow/integ/rpc/DeadEndStateWorkflow.java
src/test/java/io/iworkflow/spring/controller/ApiController.java

same for https://github.com/indeedeng/iwf-python-sdk/pull/66

IWF-397: Add channel sizes data for RPC

---

build.gradle

IWF-407: Bump release version to 2.7.2

---

build.gradle

IWF-433: Bumping release version to 2.8.0

---

build.gradle

IWF-418: Bumping release version to 2.8.1

---

src/test/java/io/iworkflow/integ/AnyCommandCombinationTest.java
src/test/java/io/iworkflow/integ/WorkflowUncompletedTest.java

IWF-537: Update iwf-idl and replace deprecated workflow type error

---

src/main/java/io/iworkflow/core/WorkflowState.java

IWF-569: Annotate getStateOptions as nullable

---

build.gradle

IWF-583 Bump release version to v2.9.0

---

build.gradle

IWF-631: Bump release to v2.10.0

---

src/test/java/io/iworkflow/integ/PersistenceTest.java
src/test/java/io/iworkflow/integ/persistence/SetDataAttributeWorkflow.java
src/test/java/io/iworkflow/integ/persistence/SetDataAttributeWorkflowState1.java
src/test/java/io/iworkflow/integ/persistence/SetSearchAttributeWorkflowState1.java

IWF-674: Improve persistence test

---

build.gradle

IWF-777: Bump release to v2.10.1
